use_frameworks!

target 'KaleyraVideo' do
  platform :ios, '15.0'

  pod 'KaleyraVideoSDK', :podspec => 'https://static.bandyer.com/corporate/iOS/releases/cocoapods/sdk/4.0.0-alpha.1/xcframework/KaleyraVideoSDK.podspec'
end

#target 'SwiftUI-Example' do
#  platform :ios, '15.0'
#
#  pod 'KaleyraVideoSDK', :podspec => 'https://static.bandyer.com/corporate/iOS/releases/cocoapods/sdk/4.0.0-alpha.1/xcframework/KaleyraVideoSDK.podspec'
#end

target 'BroadcastExtension' do
  platform :ios, '12.0'

  pod 'BandyerBroadcastExtension'
end
