# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Bandyer-iOS-SDK-Basic-Example' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Bandyer-iOS-SDK-Basic-Example
  pod 'BandyerSDK', :git => 'https://github.com/Bandyer/Bandyer-iOS-SDK.git'

end
